### ISSUE TITLE
Decks not working correctly when combining no Prototypes and All Units Blufor

### ISSUE THREAD

**Issue by 0ptus** [TheWRDNoob/Sandbox-Mod-Installer#5]
When using _No Units are Prototypes_ and _All Units are Blufor_, there are differences between a deck in the arsenal and in the game.

My deck looks like this in the Arsenal (its a general BluFor Deck, I only used Dutch and Czech units for flavor reasons):
![DeckBugArsenal](https://user-images.githubusercontent.com/62556484/144828189-f4a22000-9ec7-4b99-a1b6-1194c78c419f.png)

Ingame, there is a USSR Unit in the Supports:

![DeckBugGameSup](https://user-images.githubusercontent.com/62556484/144827284-a49b10c8-5ccf-41c1-83c9-f91b2beeac24.png)

There are also no Czech Air Units:

![DeckBugGameAir](https://user-images.githubusercontent.com/62556484/144827364-4309730e-6fc6-432c-ae60-7666c4e41c21.png)

**Comment by Griffeng** [comment]
Please use the new repo: https://github.com/Noob-Development/Sandbox-Mod-Installer

This is an old one and is not getting updated.

**Comment by 0ptus** [comment]
Sorry for apparently being blind.
